language: java

services:
- docker

env:
  jobs:
  - message = Hello to travis
  global:
  - secure: AS2Sbuhe4K+FhcJwIRwPUeDqd4JtobTEDXbSZhhuPoxHkqmqp61Cs6E+LCELl4gBoMvXYNp6VTeHqSQSz8xMkbJ5h4DX/p4dXMcvmZ5tNUjEsUPBQWdk7PVX/O/V0OVNu1JQJ7XonL4eJ0mh3zaT+s+1cHq2wtxZFxA4x1UeWufnuyS2L9xUgHEg6F9fSwTcVnyxp3QwYjL4HXbmBmvXxRZHNBkVN4D8aFH73IMuo/zOeB/+fwpheK43fmtinJSmpP7OW8XHdxaK+qMdiYIlwp4VZtNlAhP4lMP2JJILT4FyCCalW/kSsYu94Y/o4aBkEixOYkdJZdvMvTpH25q77W4rL5YJ0PEy4K1K3Ayat3gwWtKveiyBLKj/El1vi50j1uVJExJxv+Cdhov1r4qcqxCwa2a2KU/LH+Yhna0dWSs1rzDoTOSB90dDS/JVt4TavqTDcZGvnVrXqDw0FLsMZnaBNDTTR3q/StQW3hEKN9rl2wM/Q5GxDwOEJs1iC8Jz4wuV1BOgB/p6EAN6TiSfxEKJn6slUJS2v3hCOh8IqFRG9vrbuzSSMSq2KPRU5pojMITSdLIK44DRuzct6zuyPwZ+zBCEhIIC/758mvGdsXkfrdwfRp7CRNJMXkGa44CJWyck3qkvWXR+oRMtctuQlVcKRf6Qd0fBnC+0M+EWqCU=
  - secure: RQ6KEshJCKn4KL6JjQ8CnsKlHrBb0p5OWMILIzrtt7axsrHgib5kGj8tHhFlWq152BkTKeb8mUq9BbEGEnS16nAMDPkNBN/YqDNHJNgIcmX58FLboBedfTwFV6gDnGkiK3NQWyh6rXyoIbOIrTrUBk858OuDWv6LFXc9z62mLrBPfC1htAv7oamqM2NhvENtyJckFJ0Vf6r2oehJGGG2rhJTil9dtVVePzZJS0KAvXIq4e0tVCuz+OFOb69yLrhi+jyJ1CLvx3qax1Wc4amWAzhXTJL2Tx1l9grDtPoKXDVVjGfEn2lFSwZCOdhgdrfJz/jsuiT/T+bXvlS50U3iVJSPZe2KHCKQuRUUf1CglNhJYZVFcvXjfMxfz48SviYxH8nIXVUjg3eT3yUzobn2kRqP6BtlWJPzB4KeK5yKTNuAqoZ92y+lRNGRvwKx8G5b1Lr95P1vmCtvcSeJ1HRoD6IPMxtt25D60uoqatOgHqKYBTeJ0YNApFPS1MvLieJliTiAMXHBvfdiIjJ1ry8FVqKxkv+9kbLDHc0pBeQ5OiWpU3iMMiVX5q7aevpZqGMagkGqSwShWE9ddKDXUqaA8+8CrzsesymD6ALKGUJzk3RxTaLLsudzxqfLdQJsOc225fewEJgAmlyUYjWrbl8HCf2m2FUnz8g5FIQsqFGY3HE=

script:
- bash build_and_push_docker.sh

before_install:
- echo "Message of the day is $message"
- openssl aes-256-cbc -K $encrypted_ba8f794f8d33_key -iv $encrypted_ba8f794f8d33_iv
  -in google-key.json.enc -out google-key.json -d
