language: java

services:
- docker

before_install:
- docker build --build-arg JAR_FILE=target/travisdemo-0.0.1-SNAPSHOT.jar -t pgr301 .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
