language: java

services:
- docker

script:
  - bash docker_push
  - bash docker_build

env:
  global:
  - secure: FG3NkX7nAbuyPYyFiEEWS/zqw2CtnnSXmFjYb27jP1do+3WdZOHZC28Jz1JchhB2AjiGtxNzES3VNrVRO9PLEH0w99Czp/qlcYqjb2Rqy8mGUh9bW3Kw0Bbdkw/NtWAbC1Z6I4QgFq1nTSLFy+v1jQ77GID41sZzBkgE+vtDhiKH7p29eIu4gf3lH2UUcteLKzFKegobm1mFTpb3ZPgCITDyGxiJMNF36holxnEjJICR2N4aJHRurmVrlTsrLYIFqE3+T3LMu7PangUvEpiKD0YgwLlzk63XDRbojZoloIgdBdO2d+JRQBt6w2X54LrXQDr1RtKYXU+WIw7YprtxPyhim6M42DJX7b6uMDbVFa1rbeHUQtuGY73u84+wU18nmIgkwXyROWI+Y2oRJ1w+cy3ilYCh4tyx+TYpBqIdVHIL9EXMtoIrqlyGSWo/NGq5vDcLG3yoWTZyGK6+pFBsAVye4oTSqsAI/zcR1ym57K3mS3zdPvGCbblsS01CZ/TgrSYpuQygZZud5GTGK3dMQJB3ZBHGKKQ6LatN48QGaXgW2D55m4rIzSfn3Egw4TAuHBXHf4mLtm0serd1l/HEf7Jhvr+pMw74u6w0V9ZFi9g+L5eOu4eNgUk+sEJrL6ASNyqKWfB60grS6VbdMEztYx4FBk9aef/o22x9F6Jnjus=
  - secure: A45YDuUW02fALvjZ5EYpcWmjpkiE8qsWY4ogV+jO8k7PuI6te0pnwuktvcx8czQtCt48qtuFB11uLxMUkPHsQ3X9Q6wL1xhKqb6dnvG2isB0S8oDPPIE82bhmNjEFHiFRDh8yGJ+Q8sQ/LETRoANMGqGIj6r4A15qgxH4c+6LaCDvgERkUYLEoIuvDUIXXrTgugV9AXJwUAVDpbPsUNmd9KlT5eXlNZCpZ+FW0F9bdyT6mmqBvCAsgNLBWTV6LVlSmf6CEvhQcRk2zvy7sTKDjLycsWhnfyyp6FuS1Fuxjmu8zsRWjPqCi3EMKrm0il0BN2qgfiHdzc5ABVQWxQhwbVrAkl9jaB+TXyFbSY7g1KLuaNOCqQhMRnZAUvhyqKIP949LV1eF4xRc8eV5nPGCazRAYMAuvRjmKfitcfKHLz40kBm43AESSTadja+eZ14Ax2wMrQp/JXsFT8FnlBExfMs5I101cvsDVMS9WFVsFVqhi07VZro21Dnn/7GkEeUIBBaNZ23vg4MGj5eXGU5n2MuKihM408i6qudi6xhQ4gRbRthX3OXJDIixIjwCOD/Ajw/FslyV6aNv+4m4Po5qPWMFqXJFsx5H9mJARUXB1GxNVAJb/SRg8M/XsrFIvaLnBGO3IVjP2X3ScnIyS4wrcI+h9ySer0VKDcHAB+4lTE=
