language: java
services:
- docker
env:
- message="Message to travis" dayofbuild=sunday
script:
- bash debug_env_vars.sh
global:
- openssl aes-256-cbc -K $encrypted_ba8f794f8d33_key -iv $encrypted_ba8f794f8d33_iv
  -in google-key.json.enc -out google-key.json -d
